### ISSUE TITLE
From Starkware - Verify and label your contracts on block explorers 

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbon-protocol#112]
**Description**
---
Starkware strongly encourage apps to verify their contracts - both on mainnet and testnets - and put a name label on their contracts and classes.

Verify your contracts on StarkScan:
https://github.com/starkscan/starkscan-verifier

Put name tags on your contracts on StarkScan:
https://docs.google.com/forms/d/e/1FAIpQLSdqBJ311bP7VdYanA4S778LzWS0c_6nEi0yeaeCRvTM9cJPaA/viewform

Verify your contracts on Voyager:
https://voyager.online/verify

For assistance with StarkScan or Voyager, please reach out on twitter:
https://twitter.com/StarkscanCo
https://twitter.com/0xvoyageronline

**Acceptance Criteria**
---

- [ ] Verify contracts on StarkScan
- [ ] Verify contracts on Voyager
- [ ] Put name tags on contracts on StarkScan

**Comment by cloudvenger** [comment]
Apply this Issue to testnet-1 and testnet-2 #113 and #114 contracts
