### ISSUE TITLE
Farming Data visibility

### ISSUE THREAD

**Issue by Bal7hazar** [Carbonable/carbon-protocol#120]
**Description**
---
The purpose is to define and implement views and externals expected from all contracts according to UX specifications.

Here is the list of data:

### Farming index

- [x] Project name → `project.name()`
- [x] Project image → `ipfs`
- [x] Project total removal (projection) → `project.getFinalAbsorption()`
- [x] Contract TVL (Yielder + Offseter) → `(yielder.getTotalDeposited() + offseter.getTotalDeposited()) * minter.getUnitPrice()`
- [x] User total deposited value (Offset+Yield) in "unit of invest" → `(yielder.getRegisteredTokensOf()[0] + offseter.getRegisteredTokensOf()[0]) * minter.getUnitPrice()`
- [x] Claimable reward (Offset in tCO2) → `offseter.getClaimableOf()`
- [x] Claimable reward (Yield in $USDC/$ETH) → `yielder.getClaimableOf() * yielder.getEstimatedCreditCarbonPrice() / project.getTonEquivalent()`
- [x] total tCo2 generated since the beginning for a user (Offset)  → `offseter.getClaimableOf() + offseter.getClaimedOf()`
- [x] total tCo2 generated since the beginning for a user (Yield)  → `yielder.getClaimableOf() + yielder.getClaimedOf()`
- [x] total tCo2 generated since the last snapshot for a user (Yield + Offset) → `offseter.getClaimableOf() + offseter.getClaimedOf() + yielder.getClaimableOf() + yielder.getClaimedOf() - yielder.getSnapshotedOf() - yielder.getSnapshotedOffseterOf()`

### Farming Project - Yield topic

- [x] total $ generated since the last snapshot for a user →  `yielder.getClaimableOf() + yielder.getClaimedOf() - yielder.getSnapshotedOf()`
- [x] total claimable $ for a user → `vester.releasable_amount_all_vestings()`
- [x] total deposited value for a user → `yielder.getRegisteredTokensOf()[0] * minter.getUnitPrice()`

### Farming Project - Offset topic

- [x] total absorption generated since the beginning for a user → `offseter.getClaimableOf() + offseter.getClaimedOf()`
- [x] total absorption since the latest snapshot for a user →  `offseter.getClaimableOf() + offseter.getClaimedOf() - yielder.getSnapshotedOffseterOf()`
- [x] total claimable absorption for a user→ `offseter.getClaimableOf()`
- [x] total deposited value for a user → `offseter.getRegisteredTokensOf()[0] * minter.getUnitPrice()`

### Farming Project - Financial projections topic

- [x] Project absorptions → `project.getAbsorptions()`
- [x] Project times → `project.getTimes()`

### Off-chain computed data

- [ ] ~Cycle timer~
- [ ] ~Assets status~ (no relevant anymore)
- [ ] total $ generated since the beginning for a user
- [ ] Yielder APR
- [ ] Offseter APR

### Additional data (require backend listening)
- [ ] Snapshot events information
  - [ ] Project address
  - [ ] Timestamp
  - [ ] Generated absorption during the cycle for yielder, offseter and total
  - [ ] Generated $$$ for the latest cycle (avaiable after the vesting creation)
- [ ] "Climate contribution" events information
  - [ ] Project address
  - [ ] Timestamp
  - [ ] Absorption claimed
  - [ ] Contributer address

**Acceptance Criteria**
---

- [ ] All the data have a corresponding view
- [ ] All are documented and part of the online doc

**Comment by Bal7hazar** [comment]
Raw logs

```txt
[2023-1-2 17:29:58]
0x3ed04ae6ce5696a2413779f14bb4c1514b0a112798643fb96e61e7cd235b989

[ACCEPTED_ON_L2](https://testnet-2.starkscan.co/contract/0x3ed04ae6ce5696a2413779f14bb4c1514b0a112798643fb96e61e7cd235b989)
[2023-1-2 17:31:7]
0x123bc731f00f241b726b0e450caba9b11f355f984f3dfa7866df8e2b28c0763

[ACCEPTED_ON_L2](https://testnet-2.starkscan.co/contract/0x123bc731f00f241b726b0e450caba9b11f355f984f3dfa7866df8e2b28c0763)
[2023-1-2 17:31:17]
0x5ab9fa937aa6d3eef33112ec2bc6f281ae563e912bebfe90956abaa81d163d1

[ACCEPTED_ON_L2](https://testnet-2.starkscan.co/tx/0x5ab9fa937aa6d3eef33112ec2bc6f281ae563e912bebfe90956abaa81d163d1)
[2023-1-2 17:31:45]
0x5c7b71a6acc4a69430597fa208cf3fb9aa9db1afbce166f56d937e01ba538fe

[ACCEPTED_ON_L2](https://testnet-2.starkscan.co/tx/0x5c7b71a6acc4a69430597fa208cf3fb9aa9db1afbce166f56d937e01ba538fe)
[2023-1-2 17:32:25]
0xc1afa41010891f1a760396b7be389034e1426d00dd00e69353f051113ee599

[ACCEPTED_ON_L2](https://testnet-2.starkscan.co/tx/0xc1afa41010891f1a760396b7be389034e1426d00dd00e69353f051113ee599)
[2023-1-2 17:33:12]
0x68df6aa67656fe1f667b122fb9da39cbe204e408a876bdddc1fe0cb402b09cb

[ACCEPTED_ON_L2](https://testnet-2.starkscan.co/tx/0x68df6aa67656fe1f667b122fb9da39cbe204e408a876bdddc1fe0cb402b09cb)
[2023-1-2 17:33:37]
0x318aaa7616264dc5cbd5f04091b8b940d8c1955a706d74d18fe5f8c47d845f5

[ACCEPTED_ON_L2](https://testnet-2.starkscan.co/tx/0x318aaa7616264dc5cbd5f04091b8b940d8c1955a706d74d18fe5f8c47d845f5)
[2023-1-2 17:34:45]
0x7a719fa54946f5126bfa331fbe906874b8d85f72bc5f52b29ac57a6f7b20593

[ACCEPTED_ON_L2](https://testnet-2.starkscan.co/contract/0x7a719fa54946f5126bfa331fbe906874b8d85f72bc5f52b29ac57a6f7b20593)
[2023-1-2 17:35:52]
0x1039193e67761a45bd3fd21ac6c7641b1bedb44077697d77f53a4b3a11d3a83

[ACCEPTED_ON_L2](https://testnet-2.starkscan.co/contract/0x1039193e67761a45bd3fd21ac6c7641b1bedb44077697d77f53a4b3a11d3a83)
[2023-1-2 17:37:8]
0x17ff33dc0739fb469fb4d7b98571c0ef109b6b9ad3877f49b57f97feb319a59

[ACCEPTED_ON_L2](https://testnet-2.starkscan.co/contract/0x17ff33dc0739fb469fb4d7b98571c0ef109b6b9ad3877f49b57f97feb319a59)
```
