### ISSUE TITLE
Deploy protocol for new mainnet project

### ISSUE THREAD

**Issue by Bal7hazar** [Carbonable/carbon-protocol#140]
# Description

Deploy 3 new sets of contracts corresponding to the new project.

# Acceptance Criteria

## ABI

- [abi.zip](https://github.com/Carbonable/carbonable-starknet/files/10458544/abi.zip)

## Bronze

- [x] [Project](https://starkscan.co/contract/0x0541b5dd5fae206ceccaf4eeb0642e4c04d456c5bc296eab047c9414bdad4f09)
- [x] [Minter](https://starkscan.co/contract/0x5321d00440218677b1de426679b7e77381dbb846ee1ae54dc084951f99c646)

## Silver

- [x] [Project](https://starkscan.co/contract/0x6191013bbd6bcf11d69f3d60d20f7aa03439d7011bd511d13122de2275dce21)
- [x] [Minter](https://starkscan.co/contract/0x3d983ed77d966515c066d49aa35cefffc89231cb33b9593a8964f58eca8ccd8)

## Gold

- [x] [Project](https://starkscan.co/contract/0x61bcc33b0469cd072ad47813a1efd250fd36a28425d774c31c8f33c87306e8e)
- [x] [Minter](https://starkscan.co/contract/0x6458bdd463dc9cc8057c586ef5ebd80a6984c5ebcfb7b5271f25dd3d23ddfb1)

# Prerequisites

### Bronze

- [x] Name: Manjarisoa - 0x4d616e6a617269736f61
- [x] Symbol: CARB - 0x43415242
- [x] Collection Metadata

  - [x] name: Carbonable - Manjarisoa
  - [x] description: Invest in decarbonation through our Green DeFi Launchpad.
  - [x] image: https://airtable.com/appj3XhJLQdL25lLx/tblmleZkgfSWTJL8a/viw4PnUzMyAwneUtG?blocks=hide
  - [x] external_link: https://app.carbonable.io/launchpad/forest-regeneration-manjarisoa-madagascar-bronze
  - [x] banner_image_url: ipfs://Qmdjj76nkc1HQn8Tr3ertWs9eWkFMBxXQkGwjHEp6mWbig/banner.png
  - [x] youtube_url: https://youtu.be/5dZrROBmfKU

- [x] Token Metadata

  - [x] name: Carbonable - Manjarisoa
  - [x] description: Invest in decarbonation through our Green DeFi Launchpad.
  - [x] image: https://airtable.com/appj3XhJLQdL25lLx/tblmleZkgfSWTJL8a/viw4PnUzMyAwneUtG?blocks=hide
  - [x] external_link: https://app.carbonable.io/launchpad/forest-regeneration-manjarisoa-madagascar-bronze
  - [x] youtube_url: https://youtu.be/5dZrROBmfKU
  - [x] Project developer: Forest Calling Action
  - [x] Certifier: Wildsense
  - [x] Project area (ha): 20.7
  - [x] Asset area (ha): 0.0093
  - [x] Country: Madagascar
  - [x] End date: 2043
  - [x] Total project carbon units (t): 8000
  - [x] Asset's annual avg. capacity (t/y): 0.1800
  - [x] Project color: Green
  - [x] Project type: Forest
  - [x] Project category: Regeneration
  - [x] Status: Active
  - [x] Source: Carbonable

### Silver

- [x] Name: Manjarisoa - 0x4d616e6a617269736f61
- [x] Symbol: CARB - 0x43415242
- [x] Collection Metadata

  - [x] name: Carbonable - Manjarisoa
  - [x] description: Invest in decarbonation through our Green DeFi Launchpad.
  - [x] image: https://airtable.com/appj3XhJLQdL25lLx/tblmleZkgfSWTJL8a/viw4PnUzMyAwneUtG?blocks=hide
  - [x] external_link: https://app.carbonable.io/launchpad/forest-regeneration-manjarisoa-madagascar-silver
  - [x] banner_image_url: ipfs://Qmdjj76nkc1HQn8Tr3ertWs9eWkFMBxXQkGwjHEp6mWbig/banner.png
  - [x] youtube_url: https://youtu.be/5dZrROBmfKU

- [x] Token Metadata

  - [x] name: Carbonable - Manjarisoa
  - [x] description: Invest in decarbonation through our Green DeFi Launchpad.
  - [x] image: https://airtable.com/appj3XhJLQdL25lLx/tblmleZkgfSWTJL8a/viw4PnUzMyAwneUtG?blocks=hide
  - [x] external_link: https://app.carbonable.io/launchpad/forest-regeneration-manjarisoa-madagascar-silver
  - [x] youtube_url: https://youtu.be/5dZrROBmfKU
  - [x] Project developer: Forest Calling Action
  - [x] Certifier: Wildsense
  - [x] Project area (ha): 20.7
  - [x] Asset area (ha): 0.0466
  - [x] Country: Madagascar
  - [x] End date: 2043
  - [x] Total project carbon units (t): 8000
  - [x] Asset's annual avg. capacity (t/y): 0.9000
  - [x] Project color: Green
  - [x] Project type: Forest
  - [x] Project category: Regeneration
  - [x] Status: Active
  - [x] Source: Carbonable

### Gold

- [x] Name: Manjarisoa - 0x4d616e6a617269736f61
- [x] Symbol: CARB - 0x43415242
- [x] Collection Metadata

  - [x] name: Carbonable - Manjarisoa
  - [x] description: Invest in decarbonation through our Green DeFi Launchpad.
  - [x] image: https://airtable.com/appj3XhJLQdL25lLx/tblmleZkgfSWTJL8a/viw4PnUzMyAwneUtG?blocks=hide
  - [x] external_link: https://app.carbonable.io/launchpad/forest-regeneration-manjarisoa-madagascar-gold
  - [x] banner_image_url: ipfs://Qmdjj76nkc1HQn8Tr3ertWs9eWkFMBxXQkGwjHEp6mWbig/banner.png
  - [x] youtube_url: https://youtu.be/5dZrROBmfKU

- [x] Token Metadata

  - [x] name: Carbonable - Manjarisoa
  - [x] description: Invest in decarbonation through our Green DeFi Launchpad.
  - [x] image: https://airtable.com/appj3XhJLQdL25lLx/tblmleZkgfSWTJL8a/viw4PnUzMyAwneUtG?blocks=hide
  - [x] external_link: https://app.carbonable.io/launchpad/forest-regeneration-manjarisoa-madagascar-gold
  - [x] youtube_url: https://youtu.be/5dZrROBmfKU
  - [x] Project developer: Forest Calling Action
  - [x] Certifier: Wildsense
  - [x] Project area (ha): 20.7
  - [x] Asset area (ha): 0.1397
  - [x] Country: Madagascar
  - [x] End date: 2043
  - [x] Total project carbon units (t): 8000
  - [x] Asset's annual avg. capacity (t/y): 2.7003
  - [x] Project color: Green
  - [x] Project type: Forest
  - [x] Project category: Regeneration
  - [x] Status: Active
  - [x] Source: Carbonable

### Bronze

- [x] Max supply: 1672
- [x] Reserved supply: 1202+3=1205 (b2b + free mint)
- [x] Unit price: 54_500_000
- [x] Payment: µUSDC
- [x] Max buy per tx: 20

### Silver

- [x] Max supply: 80
- [x] Reserved supply: 0
- [x] Unit price: 272_500_000
- [x] Payment: µUSDC
- [x] Max buy per tx: 5

### Gold

- [x] Max supply: 10
- [x] Reserved supply: 0
- [x] Unit price: 817_500_000
- [x] Payment: µUSDC
- [x] Max buy per tx: 5

### Vestings

- [x] Payment: µUSDC

### Offseters

- [x] Min claimable: 1_000_000 gCO₂

**Comment by Bal7hazar** [comment]
# Testnet-1

## Bronze

- [ ] [Project](https://testnet.starkscan.co/contract/0x3a9d0df1831c40d6e7291753bd3eb2f9f1d205ffb8bfda02fc14b015b079530)
- [ ] [Minter](https://testnet.starkscan.co/contract/0x3a9d0)
- [ ] [Vester](https://testnet.starkscan.co/contract/0x3a9d0)
- [ ] [Offseter](https://testnet.starkscan.co/contract/0x3a9d0)
- [ ] [Yielder](https://testnet.starkscan.co/contract/0x3a9d0)

## Silver

- [ ] [Project](https://testnet.starkscan.co/contract/0x7cadb2896273458cf9ea7f4e5c042ddc13e1c70022b8f2f5c59b842803f80c7)
- [ ] [Minter](https://testnet.starkscan.co/contract/0x3a9d0)
- [ ] [Vester](https://testnet.starkscan.co/contract/0x3a9d0)
- [ ] [Offseter](https://testnet.starkscan.co/contract/0x3a9d0)
- [ ] [Yielder](https://testnet.starkscan.co/contract/0x3a9d0)

## Gold

- [ ] [Project](https://testnet.starkscan.co/contract/0x3a9d0)
- [ ] [Minter](https://testnet.starkscan.co/contract/0x3a9d0)
- [ ] [Vester](https://testnet.starkscan.co/contract/0x3a9d0)
- [ ] [Offseter](https://testnet.starkscan.co/contract/0x3a9d0)
- [ ] [Yielder](https://testnet.starkscan.co/contract/0x3a9d0)
