### ISSUE TITLE
[Impl] Fully On-chain Dynamic Token Metadata

### ISSUE THREAD

**Issue by tekkac** [Carbonable/carbon-protocol#192]
**Description**
---
Implement on-chain dynamic Metadata for Projects.
- The  tokenURI directly as JSON (MIME format).
- The value attribute should be dynamic and  the SVG image must be generated in Cairo in the MIME format.

**Acceptance Criteria**
---

- [x] Implementation of the SC
- [x] Unit Integration Tests
- [x] Marketplace image test
