### ISSUE TITLE
[Impl] Dynamize Project Metadata

### ISSUE THREAD

**Issue by tekkac** [Carbonable/carbon-protocol#194]
**Description**
---
  Implement all the dynamic metadata.
     
**Prerequisite**
--- 

Select which metadata to dynamize:
 - [x] value as an attribute 
 - [ ] Tco2/year on SVG (WIP)
 - [ ] m2 on SVG
 - [ ] zero value greyed effect
 - [ ] ...

**Acceptance Criteria**
---

- [ ] Implementation of the method
- [ ] Unit and Integration Tests
