### ISSUE TITLE
[Impl] Refactor Project Metadata

### ISSUE THREAD

**Issue by tekkac** [Carbonable/carbon-protocol#195]
**Description**
---

Refactor Project Metadata and separate Metadata from the Project contract.
Metadata should be in another repo.

**Prerequisite**
---
- [x] Set up a metadata repo

**Acceptance Criteria**
---

- [x] Implementation of metadata lib
- [x] Unit and Integration Tests

**Comment by tekkac** [comment]
Closed after discussion.
We won't use a template.
