### ISSUE TITLE
[Offseter] Define and Design the Carbonable Offseting Certificate

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbon-protocol#85]
**Description**
---
Define and Design the Carbonable Offseting Certificate.

**Questions**
---
- Which kind of Token ? (ERC-721, ERC-1155, ERC-3525, etc...)
- How is digitalized the offset certificate of the certifier ?
- Which data need to be on-chain ? off-chain ?
- Where do we store the documents / information ? (IPFS, other ?)

**Acceptance Criteria**
---
- [ ] All the questions need to be answer
- [ ] An exhaustive list of metadata must be provided (on-chain AND off-chain)
- [ ] The UI of the Carbonable certificate need to be done on Figma
